"""empty message

Revision ID: 4865c6a42a42
Revises: c6248c4d27fb
Create Date: 2021-04-29 17:32:26.319242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4865c6a42a42'
down_revision = 'c6248c4d27fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date_called')
    op.drop_column('ticket', 'date_created')
    op.drop_column('ticket', 'date_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date_end', sa.DATETIME(), nullable=True))
    op.add_column('ticket', sa.Column('date_created', sa.DATETIME(), nullable=True))
    op.add_column('ticket', sa.Column('date_called', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
