"""empty message

Revision ID: 665b0764fa51
Revises: f35a4d5da5be
Create Date: 2021-04-29 18:56:49.483265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665b0764fa51'
down_revision = 'f35a4d5da5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date_end')
    op.drop_column('ticket', 'date_called')
    op.drop_column('ticket', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date_created', sa.DATETIME(), nullable=True))
    op.add_column('ticket', sa.Column('date_called', sa.DATETIME(), nullable=True))
    op.add_column('ticket', sa.Column('date_end', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
