"""empty message

Revision ID: f35a4d5da5be
Revises: 4865c6a42a42
Create Date: 2021-04-29 17:34:16.514621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35a4d5da5be'
down_revision = '4865c6a42a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date_called', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('date_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date_end')
    op.drop_column('ticket', 'date_created')
    op.drop_column('ticket', 'date_called')
    # ### end Alembic commands ###
