"""empty message

Revision ID: f52fb077ad6b
Revises: 441f44ee32cd
Create Date: 2021-04-29 20:02:11.229441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52fb077ad6b'
down_revision = '441f44ee32cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('date_called', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('date_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'date_end')
    op.drop_column('ticket', 'date_created')
    op.drop_column('ticket', 'date_called')
    # ### end Alembic commands ###
